backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"     # where uploads are stored in the repo
public_folder: "/static/uploads"   # how the site references them

# IMPORTANT: do NOT include "publish_mode: editorial_workflow".
# Leaving it out means Publish goes straight to main (no drafts).

collections:
  - name: "site"
    label: "Site Content"
    files:
      - file: "content/site.json"
        label: "Main Site Content"
        name: "site"
        fields:
          - { label: "Headline",     name: "headline",     widget: "string" }
          - { label: "Subheadline",  name: "subheadline",  widget: "text" }
          - { label: "Button Text",  name: "buttonText",   widget: "string", default: "Book a Strategy Call" }
          - { label: "Button Link",  name: "buttonLink",   widget: "string", default: "#booking" }
          - { label: "Hero Image",   name: "image",        widget: "image", required: false }
