backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/static/uploads"

publish_mode: editorial_workflow

site_url: "https://mvmstudios.com"

collections:
  - name: "site"
    label: "Site Content"
    files:
      - file: "content/site.json"
        label: "Main Site Content"
        name: "site"
        fields:
          - { label: "Headline", name: "headline", widget: "string" }
